### ISSUE TITLE
Interest in contributions?

### ISSUE THREAD

**Issue by manwaring** [achapin/xwing-microhangars#1]
I love this tool, thank you!

I forked the repo because I wanted to add faction colors before printing off my very own (and very first!) tuckboxes for this game.  Along the way I also added some tools that make it easier (for me at least) to develop on this locally and push the changes to the repo's github page.  I'd love to contribute the changes back - let me know if that's something you're interested in otherwise I'll continue working on my own version of this for myself.

https://github.com/manwaring/xwing-microhangars

**Comment by achapin** [comment]
Hey mate,

I'd love to get a contribution integrated into the main repo! Colored icons have been on the TODO list for a while, but I just haven't gotten around to them yet. If you submit a pull request I'll give it a review.

**Comment by achapin** [comment]
Closing since there hasn't been any updates on this in a while.

If anyone is interested in making contributions, they're more than welcome!
