### ISSUE TITLE
TIE/rb Heavy box issue

### ISSUE THREAD

**Issue by KosovoBetim** [achapin/xwing-microhangars#11]
I've printed and assembled this box but the dimensions seem off so it doesn't form a properly closed box.

I thought I'd done something wrong but checked out how the layout looks upon preview and think it's a problem there.

I've attached a screenshot with sides A and B labelled that I believe have the incorrect dimensions (shortest side is too short)

![2022-06-13_12h04_07](https://user-images.githubusercontent.com/107405179/173340497-efb77e50-3a24-4a12-ac2c-99944e52cf4d.png)
.

**Comment by achapin** [comment]
The Top/Bottom are right, but the sides were definitely off. Thanks for reporting!
