### ISSUE TITLE
Layout scheme improvement

### ISSUE THREAD

**Issue by SogeMoge** [achapin/xwing-microhangars#7]
Yesterday I managed to cut out and glue together several different micro hangars from this project and form [SirWilli's](https://sirwillibald.com/games/x-wing-miniatures-games/microhangars-2-0/) as well. I found Willi's layout much easier to glue together due to cut corners and shorter length of glue panel elements (image for reference)
Also Willi's cut/fold lines are the same thickness across all the scheme which also is nice. (it's was hard to cut thick lines consistently equal)

Is it possible to get same spec on your print layout? If you will need any help with this Im happy to collaborate.
![image](https://user-images.githubusercontent.com/46896745/163588985-930e8129-2f50-43c7-a487-f97f6e397dbb.png)

**Comment by achapin** [comment]
I agree that the shortened edge of glue slides on SirWilli's definitely look and work better than my straight-edges. However, making that work with my setup would be fairly tricky - it's pretty limited to 90-degree angles. Definitely not ideal, but it does let me add new ships super quickly with just a data sheet change. So this would require some _really deep_ surgery on the system, that I'm not really planning to do anytime soon. If you want to dive into the code and submit a pull request, I'll take a look at the proposal and (assuming I can work with it in the future) bring it into the project.

**Comment by achapin** [comment]
Closing this for now since it's not planned anytime soon. I'll look into alternative solutions later on.

**Comment by achapin** [comment]
Closing this for now since it's not planned anytime soon. I'll look into alternative solutions later on.
